<html>
<body>
    <table>
        <tr>
            <td>subClassInstance.metaClass.getMetaProperty('widget1').type</td>
            <td>${subClassInstance.metaClass.getMetaProperty('widget1').type}</td>
        </tr>
        <tr>
            <td>subClassInstance.getClass().metaClass.getMetaProperty('widget1').type</td>
            <td>${subClassInstance.getClass().metaClass.getMetaProperty('widget1').type}</td>
        </tr>
    </table>
</body>
</html>
